% -------------------------------------------------------------------------
% Example_Driver.m
% -------------------------------------------------------------------------
% An example script to run an O-SNAP analysis on Example_H3K27me3_ALL\
% using the command window or a script
% -------------------------------------------------------------------------
% Code written by:
%   Hannah Kim          Lakadamyali lab, University of Pennsylvania (USA)
% Contact:
%   hannah.kim3@pennmedicine.upenn.edu
%   melike.lakadamyali@pennmedicine.upenn.edu
% If used, please cite:
%   ....
% -------------------------------------------------------------------------

%% SET UP
msgbox('Download example data from DOI: 10.6084/m9.figshare.29533940')
disp('Download example data from DOI: 10.6084/m9.figshare.29533940')
root_dir = uigetdir(fullfile(getenv("USERPROFILE")),"Select path to Example_H3K27me3_ALL"); %% REPLACE WITH PATH TO DIRECTORY CONTAINING ANALYSIS DIRECTORY
analysis_name = "OSNAP_Output";
phenotypes = {'CtrlhFb','CtrlmESC','HK06h','HK24h','HK48h'};
replicates = {'20201118','20201203','20201209','20210824'};
run_options = get_OSNAP_default_options();
%% RUN
OSNAP_data = run_OSNAP_pipeline(root_dir,analysis_name,...
    phenotypes, ...
    replicates,...
    "run_extract_features", run_options.run_extract_features,...
    "run_generate_table", run_options.run_generate_table,...
    "run_comparison", run_options.run_comparison,...
    "run_generate_batches", run_options.run_generate_batches,...
    "run_feature_selection", run_options.run_feature_selection,...
    "run_PCA", run_options.run_PCA,...
    "run_classification_all", run_options.run_classification_all,...
    "run_classification_batch", run_options.run_classification_batch,...
    "run_venn", run_options.run_venn,...
    "run_plot_violin", run_options.run_plot_violin,...
    "run_plot_radial", run_options.run_plot_radial,...
    "run_FSEA", run_options.run_FSEA,...
    ... generate batch options
    "split_method", run_options.split_method,...
    "proportion", run_options.proportion,...
    "test_train_k", run_options.test_train_k,...
    ... feature select options
    "feature_select_max_idx", run_options.feature_select_max_idx,...
    ... PCA options
    "num_components_explained", run_options.num_components_explained,...
    ... classification options
    "n_models_per_type", run_options.n_models_per_type,...
    ... comparison options
    "alpha", run_options.alpha,...
    "fold_change_threshold", run_options.fold_change_threshold,...
    ... FSEA options
    "feature_universe_names", run_options.feature_universe_names,...
    "FSEA_rank_type", run_options.FSEA_rank_type,...
    ... other options
    "n_processes", run_options.n_processes,...
    "suffix", run_options.suffix,...
    "save", run_options.save,...
    "save_if_error", run_options.save_if_error,...
    "check_overwrite", run_options.check_overwrite);