% -------------------------------------------------------------------------
% get_OSNAP_default_options.m
% -------------------------------------------------------------------------
% Outputs defalult run options for an O-SNAP analysis
%
% Example on how to use it:
%   options = get_OSNAP_default_options()
% -------------------------------------------------------------------------
% Output:
%   - options: Struct array of parameter values for O-SNAP analysis
% -------------------------------------------------------------------------
% Code written by:
%   Hannah Kim          Lakadamyali lab, University of Pennsylvania (USA)
% Contact:
%   hannah.kim3@pennmedicine.upenn.edu
%   melike.lakadamyali@pennmedicine.upenn.edu
% If used, please cite:
%   ....
% -------------------------------------------------------------------------
%%
function options = get_OSNAP_default_options()
options = struct(...
    ... run options
    "run_extract_features", 1,...
    "run_generate_table", 1,...
    "run_comparison", 1,...
    "run_generate_batches", 1,...
    "run_feature_selection", 1,...
    "run_PCA", 1,...
    "run_classification_all", 0,...
    "run_classification_batch", 1,...
    "run_venn", 0,...
    "run_plot_violin", 0,...
    "run_plot_radial", 0,...
    "run_FSEA", 0,...
    ... generate batch options
    "split_method", "k-fold",...
    "proportion", 0.2,...
    "test_train_k", 5,...
    ... feature select options
    "feature_select_max_idx", 12,...
    ... PCA options
    "num_components_explained", 0.75,...
    ... classification options
    "n_models_per_type", 5,...
    ... comparison options
    "alpha", 0.05,...
    "fold_change_threshold", 2,...
    ... FSEA options
    "feature_universe_names", "universe_1",...
    "FSEA_rank_type", "S2N",...
    ... other options
    "n_processes", maxNumCompThreads,...
    "suffix", "",...
    "save", 1,...
    "save_if_error", 1,...
    "check_overwrite", 0);
end