try
    oldFolder = cd('C:\Users\HannahKim\Documents\STORM\Nuclipse\InsidePolyFolder');
    insidepoly_install
    cd(oldFolder)
catch ME
    if(strcmp(ME.identifier,'MATLAB:mex:NoCompilerFound_link_Win64'))
        msgbox({'Install C compiler for Matlab:',...
            '   1. On the MATLAB Home tab, in the Environment section, click Add-Ons > Get Add-Ons.', ...
            '   2. Search for MinGW or select from Features.',...
            '   3. Follow instructions on page to install MinGW-w64 C/C++/Fortran Compiler.',...
            '      Note: Different MATLAB versions may have different installation steps.',...
            '   4. Restart Matlab.'})
    end
    rethrow(ME)
end