function saveVoronoiClusters(filePath, data)
        % area_thresholds = data.area_thresholds;
        % min_number_of_localizations = data.min_number_of_localizations;
        % clusters = data.clusters;
        % clusterNLocs = data.clusterNLocs;
        % clusterArea = data.clusterArea;
        % clusterDensity = data.clusterDensity;
        % clusterGyrationR = data.clusterGyrationR;
        % if exist(filePath,'file')
        %     save(filePath,...
        %         'area_thresholds',...
        %         'min_number_of_localizations',...
        %         'clusters',...
        %         'clusterNLocs',...
        %         'clusterArea',...
        %         'clusterDensity',...
        %         'clusterGyrationR',...
        %         "-append");
        % end
        if exist(filePath,'file')
            save(filePath,...
                "-struct",...
                "data",...
                "-append")
        else
            save(filePath,...
                "-struct",...
                "data")
        end
end