function saveVoronoiAnalysisData(filePath, data)
    if exist(filePath,'file')
        save(filePath,...
            "-struct",...
            "data",...
            "-append")
    else
        save(filePath,...
            "-struct",...
            "data")
    end
end