function feature_universes = get_feature_universes(feature_universe_names)
arguments
    feature_universe_names string = ["universe_1"];
end
feature_universes = cell(1,length(feature_universe_names));
for i=1:length(feature_universe_names)
    universe = feval("get_" + lower(feature_universe_names(i)));
    feature_universes{i}.name = feature_universe_names(i);
    feature_universes{i}.feature_set = structfun(@(x) string(x(:,1)), universe, 'uni', 0);
    feature_universes{i}.direction = structfun(@(x) cell2mat(x(:,2)), universe, 'uni', 0);
end
end
% the direction (whether it is for or against the direction listed in the
% feature universe) is indicated with +/-1 where +1 indicates an increase
% in the feature value indicates FOR while -1 means an increase in the 
% feature value goes AGAINST the change described by the feature set
%% feature set definition
function universe = get_universe_1()
universe.larger_nucleus = {...
    "major_axis",1;...
    "minor_axis",1;...
    "convex_area",1;...
    "fiber_length",1;...
    "fiber_width",1;...
    "perimeter",1;...
    "convex_perimeter",1;...
    "nucleus_radius",1;...
    };
universe.rounder_nucleus = {...
    "circularity",1;...
    "convex_circularity",1;...
    "convexity",1;...
    "solidity",1;...
    "minor_axis_norm_area",1;...
    "log_border_curvature_std",1;...
    "elastic_energy",-1;...
    "bending_energy",-1;...
    "gyration_radius",-1;...
    "aspect_ratio",-1;...
    "form_ratio",-1;...
    "rectangularity",-1;...
    "curl",-1;...
    "major_axis_norm_area",-1;...
    "elastic_energy_norm_area",-1;...
    "bending_energy_norm_area",-1;...
    "log_border_curvature_mean",-1;...
    "log_border_curvature_skewness",-1;...
    "log_model_lad_segment_length_mean",-1;...
    "eigenvalues_ratio",-1;...
    "eigenentropy",-1;...
    };
universe.more_localizations = { ...
    "locs_number",1;...
    "interior_dbscan_cluster_n_locs",1;...
    "periphery_dbscan_cluster_n_locs",1;...
    "log_interior_dbscan_cluster_n_locs_mean",1;...
    "log_periphery_dbscan_cluster_n_locs_mean",1;...
    };
universe.denser_localizations_global = {...
    "locs_density",1;...
    "log_voronoi_density_mean",1;...
    "reduced_log_voronoi_density_mean",1;...
    "log_voronoi_density_40",1;...
    "log_voronoi_density_70",1;...
    "reduced_log_voronoi_density_40",1;...
    "reduced_log_voronoi_density_70",1;...
    };
universe.denser_localizations_interior = {...
    "interior_loc_density",1;...
    "radial_loc_density_ring_01",1;...
    "radial_loc_density_ring_02",1;...
    "radial_loc_density_ring_03",1;...
    "radial_loc_density_ring_04",1;...
    "radial_loc_density_ring_05",1;...
    "radial_loc_density_ring_06",1;...
    "radial_loc_density_ring_07",1;...
    "radial_loc_density_ring_08",1;...
    };
universe.denser_localizations_periphery = {...
    "periphery_loc_density",1;...
    "periphery_to_interior_loc_density_ratio",1;...
    "radial_loc_density_ring_09",1;...
    "radial_loc_density_ring_10",1;...
    };
% universe.more_heterogenous_localizations_global = {...
%     "log_voronoi_density_std",1;...
%     "log_voronoi_density_skewness",1;...
%     };
universe.larger_clusters = {...
    "voronoi_cluster_018nm^2_log_radius_mean",1;...
    "voronoi_cluster_032nm^2_log_radius_mean",1;...
    "voronoi_cluster_056nm^2_log_radius_mean",1;...
    "voronoi_cluster_100nm^2_log_radius_mean",1;...
    "log_interior_dbscan_cluster_radius_mean",1;...
    "log_periphery_dbscan_cluster_radius_mean",1;...
    };
universe.rounder_clusters = {...
    "voronoi_cluster_018nm^2_log_gyration_radius_mean",-1;...
    "voronoi_cluster_032nm^2_log_gyration_radius_mean",-1;...
    "voronoi_cluster_056nm^2_log_gyration_radius_mean",-1;...
    "voronoi_cluster_100nm^2_log_gyration_radius_mean",-1;...
    };
universe.denser_clusters = {...
    "voronoi_cluster_018nm^2_log_density_mean",1;...
    "voronoi_cluster_032nm^2_log_density_mean",1;...
    "voronoi_cluster_056nm^2_log_density_mean",1;...
    "voronoi_cluster_100nm^2_log_density_mean",1;...
    "log_interior_dbscan_cluster_density_mean",1;...
    "log_periphery_dbscan_cluster_density_mean",1;...
    };
universe.more_clusters_global = {...
    "voronoi_cluster_018nm^2_clusters_per_nucleus_area",1;...
    "voronoi_cluster_032nm^2_clusters_per_nucleus_area",1;...
    "voronoi_cluster_056nm^2_clusters_per_nucleus_area",1;...
    "voronoi_cluster_100nm^2_clusters_per_nucleus_area",1;...
    };
universe.more_clusters_interior = {...
    "interior_cluster_density",1;...
    "interior_dbscan_cluster_n_clusters",1;...
    "radial_dbscan_cluster_density_ring_01",1;...
    "radial_dbscan_cluster_density_ring_02",1;...
    "radial_dbscan_cluster_density_ring_03",1;...
    "radial_dbscan_cluster_density_ring_04",1;...
    "radial_dbscan_cluster_density_ring_05",1;...
    "radial_dbscan_cluster_density_ring_06",1;...
    "radial_dbscan_cluster_density_ring_07",1;...
    "radial_dbscan_cluster_density_ring_08",1;...
    };
universe.more_clusters_periphery= {...
    "periphery_cluster_density",1;...
    "periphery_dbscan_cluster_n_clusters",1;...
    "radial_dbscan_cluster_density_ring_09",1;...
    "radial_dbscan_cluster_density_ring_10",1;...
    };
universe.more_heterogenous_clusters_global = {...
    "voronoi_cluster_018nm^2_log_radius_std",1;...
    "voronoi_cluster_032nm^2_log_radius_std",1;...
    "voronoi_cluster_056nm^2_log_radius_std",1;...
    "voronoi_cluster_100nm^2_log_radius_std",1;...
    "voronoi_cluster_018nm^2_log_density_std",1;...
    "voronoi_cluster_032nm^2_log_density_std",1;...
    "voronoi_cluster_056nm^2_log_density_std",1;...
    "voronoi_cluster_100nm^2_log_density_std",1;...
    "voronoi_cluster_018nm^2_log_gyration_radius_std",1;...
    "voronoi_cluster_032nm^2_log_gyration_radius_std",1;...
    "voronoi_cluster_056nm^2_log_gyration_radius_std",1;...
    "voronoi_cluster_100nm^2_log_gyration_radius_std",1;...
    % "voronoi_cluster_018nm^2_log_radius_skewness",1;...
    % "voronoi_cluster_032nm^2_log_radius_skewness",1;...
    % "voronoi_cluster_056nm^2_log_radius_skewness",1;...
    % "voronoi_cluster_100nm^2_log_radius_skewness",1;...
    % "voronoi_cluster_018nm^2_log_density_skewness",1;...
    % "voronoi_cluster_032nm^2_log_density_skewness",1;...
    % "voronoi_cluster_056nm^2_log_density_skewness",1;...
    % "voronoi_cluster_100nm^2_log_density_skewness",1;...
    % "voronoi_cluster_018nm^2_log_gyration_radius_skewness",1;...
    % "voronoi_cluster_032nm^2_log_gyration_radius_skewness",1;...
    % "voronoi_cluster_056nm^2_log_gyration_radius_skewness",1;...
    % "voronoi_cluster_100nm^2_log_gyration_radius_skewness",1;...
    };
universe.more_heterogenous_clusters_interior = {...
    "log_interior_dbscan_cluster_radius_std",1;...
    "log_interior_dbscan_cluster_density_std",1;...
    "log_interior_dbscan_cluster_n_locs_std",1;...
    "log_interior_dbscan_cluster_spacing_std",1;...
    "radial_loc_density_ring_gradient_major_axis",1;...
    "radial_loc_density_ring_gradient_minor_axis",1;...
    "radial_dbscan_cluster_density_ring_gradient_major_axis",1;...
    "radial_dbscan_cluster_density_ring_gradient_minor_axis",1;...
    % "log_interior_dbscan_cluster_radius_skewness",1;...
    % "log_interior_dbscan_cluster_density_skewness",1;...
    % "log_interior_dbscan_cluster_n_locs_skewness",1;...
    % "log_interior_dbscan_cluster_spacing_skewness",1;...
    };
universe.more_heterogenous_clusters_periphery = {...
    "log_periphery_dbscan_cluster_n_locs_std",1;...
    "log_periphery_dbscan_cluster_radius_std",1;...
    "log_periphery_dbscan_cluster_density_std",1;...
    "log_model_lad_segment_length_std",1;...
    "log_model_lad_segment_thickness_std",1;...
    % "log_periphery_dbscan_cluster_n_locs_skewness",1;...
    % "log_periphery_dbscan_cluster_radius_skewness",1;...
    % "log_periphery_dbscan_cluster_density_skewness",1;...
    % "log_model_lad_segment_length_skewness",1;...
    % "log_model_lad_segment_thickness_skewness",1;...
    };
universe.more_enrichment_at_periphery = {...
    "periphery_to_interior_dbscan_cluster_density_ratio",1;...
    "log_model_lad_segment_thickness_mean",1;...
    "model_lad_thickness",1;...
    "log_interior_dbscan_cluster_spacing_mean",1;...
    };
end
