function feature_universes = get_feature_universes(feature_universe_names)
arguments
    feature_universe_names string = ["feature_universe_1","feature_universe_2","feature_universe_3"];
end
feature_universes = cell(1,length(feature_universe_names));
for i=1:length(feature_universe_names)
    feature_universes{i}.name = feature_universe_names(i);
    feature_universes{i}.universe = feval("get_" + lower(feature_universe_names(i)));
end
end
%% feature family definition 1
function feature_universe = get_feature_universe_1()
    % Nucleus morphology
    feature_universe.nucleus_morphology = [ ...
        "major_axis",...
        "minor_axis",...
        "convex_area",...
        "gyration_radius",...
        "eigenvalues_ratio",...
        "eigenentropy",...
        "aspect_ratio",...
        "form_ratio",...
        "rectangularity",...
        "circularity",...
        "convexity",...
        "solidity",...
        "fiber_length",...
        "fiber_width",...
        "curl",...
        "major_axis_norm_area",...
        "minor_axis_norm_area",...
        "nucleus_radius",...
        "perimeter",...
        "convex_perimeter",...
        "convex_circularity",...
        "elastic_energy",...
        "bending_energy",...
        "elastic_energy_norm_area",...
        "bending_energy_norm_area"...
        ];
    % Whole-nucleus chromatin distribution
    feature_universe.chromatin_distribution = [ ...
        "locs_density",...
        "locs_number",...
        "voronoi_density_40",...
        "voronoi_density_70",...
        "reduced_log_voronoi_density_median",...
        "reduced_log_voronoi_density_std",...
        "reduced_log_voronoi_density_skewness"...
        ];
    % Chromatin radial analysis
    feature_universe.radial = [ ...
        "periphery_density",...
        "interior_density",...
        "radial_density_ring_01",...
        "radial_density_ring_02",...
        "radial_density_ring_03",...
        "radial_density_ring_04",...
        "radial_density_ring_05",...
        "radial_density_ring_06",...
        "radial_density_ring_07",...
        "radial_density_ring_08",...
        "radial_density_ring_09",...
        "radial_density_ring_10",...
        "radial_density_ring_gradient_major_axis",...
        "radial_density_ring_gradient_minor_axis"...
        ];
    % Heterochromatin radial analysis
    feature_universe.heterochromatin_radial = [ ...
        "periphery_hetero_density",...
        "interior_hetero_density",...
        "radial_heterochromatin_density_ring_01",...
        "radial_heterochromatin_density_ring_02",...
        "radial_heterochromatin_density_ring_03",...
        "radial_heterochromatin_density_ring_04",...
        "radial_heterochromatin_density_ring_05",...
        "radial_heterochromatin_density_ring_06",...
        "radial_heterochromatin_density_ring_07",...
        "radial_heterochromatin_density_ring_08",...
        "radial_heterochromatin_density_ring_09",...
        "radial_heterochromatin_density_ring_10",...
        "radial_heterochromatin_density_ring_gradient_major_axis",...
        "radial_heterochromatin_density_ring_gradient_minor_axis"...
        ];
    % Voronoi clustering
    feature_universe.voronoi_clustering = [ ...
        "voronoi_cluster_010nm_area_median",...
        "voronoi_cluster_010nm_area_std",...
        "voronoi_cluster_010nm_area_skewness",...
        "voronoi_cluster_010nm_density_median",...
        "voronoi_cluster_010nm_density_std",...
        "voronoi_cluster_010nm_density_skewness",...
        "voronoi_cluster_010nm_gyration_R_median",...
        "voronoi_cluster_010nm_gyration_R_std",...
        "voronoi_cluster_010nm_gyration_R_skewness",...
        "voronoi_cluster_010nm_n_locs_median",...
        "voronoi_cluster_010nm_n_locs_std",...
        "voronoi_cluster_010nm_n_locs_skewness",...
        "voronoi_cluster_018nm_area_median",...
        "voronoi_cluster_018nm_area_std",...
        "voronoi_cluster_018nm_area_skewness",...
        "voronoi_cluster_018nm_density_median",...
        "voronoi_cluster_018nm_density_std",...
        "voronoi_cluster_018nm_density_skewness",...
        "voronoi_cluster_018nm_gyration_R_median",...
        "voronoi_cluster_018nm_gyration_R_std",...
        "voronoi_cluster_018nm_gyration_R_skewness",...
        "voronoi_cluster_018nm_n_locs_median",...
        "voronoi_cluster_018nm_n_locs_std",...
        "voronoi_cluster_018nm_n_locs_skewness",...
        "voronoi_cluster_032nm_area_median",...
        "voronoi_cluster_032nm_area_std",...
        "voronoi_cluster_032nm_area_skewness",...
        "voronoi_cluster_032nm_density_median",...
        "voronoi_cluster_032nm_density_std",...
        "voronoi_cluster_032nm_density_skewness",...
        "voronoi_cluster_032nm_gyration_R_median",...
        "voronoi_cluster_032nm_gyration_R_std",...
        "voronoi_cluster_032nm_gyration_R_skewness",...
        "voronoi_cluster_032nm_n_locs_median",...
        "voronoi_cluster_032nm_n_locs_std",...
        "voronoi_cluster_032nm_n_locs_skewness",...
        "voronoi_cluster_056nm_area_median",...
        "voronoi_cluster_056nm_area_std",...
        "voronoi_cluster_056nm_area_skewness",...
        "voronoi_cluster_056nm_density_median",...
        "voronoi_cluster_056nm_density_std",...
        "voronoi_cluster_056nm_density_skewness",...
        "voronoi_cluster_056nm_gyration_R_median",...
        "voronoi_cluster_056nm_gyration_R_std",...
        "voronoi_cluster_056nm_gyration_R_skewness",...
        "voronoi_cluster_056nm_n_locs_median",...
        "voronoi_cluster_056nm_n_locs_std",...
        "voronoi_cluster_056nm_n_locs_skewness",...
        "voronoi_cluster_100nm_area_median",...
        "voronoi_cluster_100nm_area_std",...
        "voronoi_cluster_100nm_area_skewness",...
        "voronoi_cluster_100nm_density_median",...
        "voronoi_cluster_100nm_density_std",...
        "voronoi_cluster_100nm_density_skewness",...
        "voronoi_cluster_100nm_gyration_R_median",...
        "voronoi_cluster_100nm_gyration_R_std",...
        "voronoi_cluster_100nm_gyration_R_skewness",...
        "voronoi_cluster_100nm_n_locs_median",...
        "voronoi_cluster_100nm_n_locs_std",...
        "voronoi_cluster_100nm_n_locs_skewness"...
        "voronoi_cluster_010nm_clusters_per_area",...
        "voronoi_cluster_018nm_clusters_per_area",...
        "voronoi_cluster_032nm_clusters_per_area",...
        "voronoi_cluster_056nm_clusters_per_area",...
        "voronoi_cluster_100nm_clusters_per_area"...
        ];
    % Heterochromatin cluster analysis
    feature_universe.heterochromatin_cluster = [ ...
        "hetero_radius_median",...
        "hetero_radius_std",...
        "hetero_radius_skewness",...
        "hetero_density_median",...
        "hetero_density_std",...
        "hetero_density_skewness",...
        "hetero_n_locs_median",...
        "hetero_n_locs_std",...
        "hetero_n_locs_skewness"...
        ];
    % Lamin-associated domain (LAD)
    feature_universe.lads = [ ...
        "lads_area_median",...
        "lads_area_std",...
        "lads_area_skewness",...
        "lads_density_median",...
        "lads_density_std",...
        "lads_density_skewness",...
        "lads_n_locs_median",...
        "lads_n_locs_std",...
        "lads_n_locs_skewness",...
        "lads_seg_len_median",...
        "lads_seg_len_std",...
        "lads_seg_len_skewness",...
        "lads_seg_thickness_median",...
        "lads_seg_thickness_std",...
        "lads_seg_thickness_skewness",...
        "spacing_median",...
        "spacing_std",...
        "spacing_skewness",...
        "border_curvature_median",...
        "border_curvature_std",...
        "border_curvature_skewness",...
        "lads_n_locs",...
        "non_lads_n_locs",...
        "lads2total_n_locs",...
        "lads_n_clusters",...
        "non_lads_n_clusters",...
        "lads2total_n_clusters"...
    ];
end

%% feature family definition 2
function feature_universe = get_feature_universe_2()
    % Nucleus morphology
    feature_universe.nucleus_morphology = [ ...
        "major_axis",...
        "minor_axis",...
        "convex_area",...
        "gyration_radius",...
        "eigenvalues_ratio",...
        "eigenentropy",...
        "aspect_ratio",...
        "form_ratio",...
        "rectangularity",...
        "circularity",...
        "convexity",...
        "convex_circularity",...
        "solidity",...
        "fiber_length",...
        "fiber_width",...
        "curl",...
        "major_axis_norm_area",...
        "minor_axis_norm_area",...
        "nucleus_radius"...
        ];
    % Nucleus morphology (boundary-specific)
    feature_universe.nucleus_boundary = [ ...
        "perimeter",...
        "convex_perimeter",...
        "elastic_energy",...
        "bending_energy",...
        "elastic_energy_norm_area"...
        "bending_energy_norm_area"...
        ];
    % Whole-nucleus chromatin distribution
    feature_universe.chromatin_distribution = [ ...
        "locs_density",...
        "locs_number",...
        "voronoi_density_40",...
        "voronoi_density_70",...
        "reduced_log_voronoi_density_median",...
        "reduced_log_voronoi_density_std",...
        "reduced_log_voronoi_density_skewness"...
        ];
    % Chromatin radial analysis
    feature_universe.radial_interior = [ ...
        "interior_density",...
        "radial_density_ring_01",...
        "radial_density_ring_02",...
        "radial_density_ring_03",...
        "radial_density_ring_04",...
        "radial_density_ring_05",...
        "radial_density_ring_06",...
        "radial_density_ring_07",...
        "radial_density_ring_08"...
        ];
    feature_universe.radial_periphery = [ ...
        "periphery_density",...
        "radial_density_ring_09",...
        "radial_density_ring_10"...
        ];
    feature_universe.radial_gradient = [ ...
        "radial_density_ring_gradient_major_axis",...
        "radial_density_ring_gradient_minor_axis"...
        ];
    % Heterochromatin radial analysis
    feature_universe.radial_heterochromatin_interior = [ ...
        "interior_hetero_density",...
        "radial_heterochromatin_density_ring_01",...
        "radial_heterochromatin_density_ring_02",...
        "radial_heterochromatin_density_ring_03",...
        "radial_heterochromatin_density_ring_04",...
        "radial_heterochromatin_density_ring_05",...
        "radial_heterochromatin_density_ring_06",...
        "radial_heterochromatin_density_ring_07",...
        "radial_heterochromatin_density_ring_08"...
        ];
    feature_universe.radial_heterochromatin_periphery = [ ...
        "periphery_hetero_density",...
        "radial_heterochromatin_density_ring_09",...
        "radial_heterochromatin_density_ring_10"...
        ];
    feature_universe.radial_heterochromatin_gradient = [ ...
        "radial_heterochromatin_density_ring_gradient_major_axis",...
        "radial_heterochromatin_density_ring_gradient_minor_axis"...
        ];
    % Voronoi clustering
    feature_universe.voronoi_clustering_010nm = [ ...
        "voronoi_cluster_010nm_area_median",...
        "voronoi_cluster_010nm_area_std",...
        "voronoi_cluster_010nm_area_skewness",...
        "voronoi_cluster_010nm_density_median",...
        "voronoi_cluster_010nm_density_std",...
        "voronoi_cluster_010nm_density_skewness",...
        "voronoi_cluster_010nm_gyration_R_median",...
        "voronoi_cluster_010nm_gyration_R_std",...
        "voronoi_cluster_010nm_gyration_R_skewness",...
        "voronoi_cluster_010nm_n_locs_median",...
        "voronoi_cluster_010nm_n_locs_std",...
        "voronoi_cluster_010nm_n_locs_skewness"...
        "voronoi_cluster_010nm_clusters_per_area"...
        ];
    feature_universe.voronoi_clustering_018nm = [ ...
        "voronoi_cluster_018nm_area_median",...
        "voronoi_cluster_018nm_area_std",...
        "voronoi_cluster_018nm_area_skewness",...
        "voronoi_cluster_018nm_density_median",...
        "voronoi_cluster_018nm_density_std",...
        "voronoi_cluster_018nm_density_skewness",...
        "voronoi_cluster_018nm_gyration_R_median",...
        "voronoi_cluster_018nm_gyration_R_std",...
        "voronoi_cluster_018nm_gyration_R_skewness",...
        "voronoi_cluster_018nm_n_locs_median",...
        "voronoi_cluster_018nm_n_locs_std",...
        "voronoi_cluster_018nm_n_locs_skewness"...
        "voronoi_cluster_018nm_clusters_per_area"...
        ];
    feature_universe.voronoi_clustering_032nm = [ ...
        "voronoi_cluster_032nm_area_median",...
        "voronoi_cluster_032nm_area_std",...
        "voronoi_cluster_032nm_area_skewness",...
        "voronoi_cluster_032nm_density_median",...
        "voronoi_cluster_032nm_density_std",...
        "voronoi_cluster_032nm_density_skewness",...
        "voronoi_cluster_032nm_gyration_R_median",...
        "voronoi_cluster_032nm_gyration_R_std",...
        "voronoi_cluster_032nm_gyration_R_skewness",...
        "voronoi_cluster_032nm_n_locs_median",...
        "voronoi_cluster_032nm_n_locs_std",...
        "voronoi_cluster_032nm_n_locs_skewness"...
        "voronoi_cluster_032nm_clusters_per_area"...
        ];
    feature_universe.voronoi_clustering_056nm = [ ...
        "voronoi_cluster_056nm_area_median",...
        "voronoi_cluster_056nm_area_std",...
        "voronoi_cluster_056nm_area_skewness",...
        "voronoi_cluster_056nm_density_median",...
        "voronoi_cluster_056nm_density_std",...
        "voronoi_cluster_056nm_density_skewness",...
        "voronoi_cluster_056nm_gyration_R_median",...
        "voronoi_cluster_056nm_gyration_R_std",...
        "voronoi_cluster_056nm_gyration_R_skewness",...
        "voronoi_cluster_056nm_n_locs_median",...
        "voronoi_cluster_056nm_n_locs_std",...
        "voronoi_cluster_056nm_n_locs_skewness"...
        "voronoi_cluster_056nm_clusters_per_area"...
        ];
    feature_universe.voronoi_clustering_100nm = [ ...
        "voronoi_cluster_100nm_area_median",...
        "voronoi_cluster_100nm_area_std",...
        "voronoi_cluster_100nm_area_skewness",...
        "voronoi_cluster_100nm_density_median",...
        "voronoi_cluster_100nm_density_std",...
        "voronoi_cluster_100nm_density_skewness",...
        "voronoi_cluster_100nm_gyration_R_median",...
        "voronoi_cluster_100nm_gyration_R_std",...
        "voronoi_cluster_100nm_gyration_R_skewness",...
        "voronoi_cluster_100nm_n_locs_median",...
        "voronoi_cluster_100nm_n_locs_std",...
        "voronoi_cluster_100nm_n_locs_skewness"...
        "voronoi_cluster_100nm_clusters_per_area"...
        ];
    % Heterochromatin cluster analysis
    feature_universe.heterochromatin_cluster = [ ...
        "hetero_radius_median",...
        "hetero_radius_std",...
        "hetero_radius_skewness",...
        "hetero_density_median",...
        "hetero_density_std",...
        "hetero_density_skewness",...
        "hetero_n_locs_median",...
        "hetero_n_locs_std",...
        "hetero_n_locs_skewness"...
        ];
    % Lamin-associated domain (LAD)
    feature_universe.lads = [ ...
        "lads_area_median",...
        "lads_area_std",...
        "lads_area_skewness",...
        "lads_density_median",...
        "lads_density_std",...
        "lads_density_skewness",...
        "lads_n_locs_median",...
        "lads_n_locs_std",...
        "lads_n_locs_skewness",...
        "lads_seg_len_median",...
        "lads_seg_len_std",...
        "lads_seg_len_skewness",...
        "lads_seg_thickness_median",...
        "lads_seg_thickness_std",...
        "lads_seg_thickness_skewness",...
        "spacing_median",...
        "spacing_std",...
        "spacing_skewness",...
        "border_curvature_median",...
        "border_curvature_std",...
        "border_curvature_skewness",...
        "lads_n_locs",...
        "non_lads_n_locs",...
        "lads2total_n_locs",...
        "lads_n_clusters",...
        "non_lads_n_clusters",...
        "lads2total_n_clusters"...
        ];
end
%% feature family definition 3
function feature_universe = get_feature_universe_3()
    % Nucleus morphology
    feature_universe.nucleus_morphology = [ ...
        "major_axis",...
        "minor_axis",...
        "convex_area",...
        "gyration_radius",...
        "eigenvalues_ratio",...
        "eigenentropy",...
        "aspect_ratio",...
        "form_ratio",...
        "rectangularity",...
        "circularity",...
        "convexity",...
        "convex_circularity",...
        "solidity",...
        "fiber_length",...
        "fiber_width",...
        "curl",...
        "major_axis_norm_area",...
        "minor_axis_norm_area",...
        "nucleus_radius",...
        "perimeter",...
        "convex_perimeter",...
        "elastic_energy",...
        "bending_energy",...
        "elastic_energy_norm_area",...
        "bending_energy_norm_area"...
        ];
    % Whole-nucleus chromatin distribution
    feature_universe.chromatin_distribution = [ ...
        "locs_density",...
        "locs_number",...
        "voronoi_density_40",...
        "voronoi_density_70",...
        "reduced_log_voronoi_density_median",...
        "reduced_log_voronoi_density_std",...
        "reduced_log_voronoi_density_skewness"...
        ];
    % Chromatin radial analysis
    feature_universe.radial = [ ...
        "periphery_density",...
        "interior_density",...
        "radial_density_ring_01",...
        "radial_density_ring_02",...
        "radial_density_ring_03",...
        "radial_density_ring_04",...
        "radial_density_ring_05",...
        "radial_density_ring_06",...
        "radial_density_ring_07",...
        "radial_density_ring_08",...
        "radial_density_ring_09",...
        "radial_density_ring_10",...
        "radial_density_ring_gradient_major_axis",...
        "radial_density_ring_gradient_minor_axis"...
        ];
    % Heterochromatin radial analysis
    feature_universe.heterochromatin_radial = [ ...
        "periphery_hetero_density",...
        "interior_hetero_density",...
        "radial_heterochromatin_density_ring_01",...
        "radial_heterochromatin_density_ring_02",...
        "radial_heterochromatin_density_ring_03",...
        "radial_heterochromatin_density_ring_04",...
        "radial_heterochromatin_density_ring_05",...
        "radial_heterochromatin_density_ring_06",...
        "radial_heterochromatin_density_ring_07",...
        "radial_heterochromatin_density_ring_08",...
        "radial_heterochromatin_density_ring_09",...
        "radial_heterochromatin_density_ring_10",...
        "radial_heterochromatin_density_ring_gradient_major_axis",...
        "radial_heterochromatin_density_ring_gradient_minor_axis"...
        ];
    % Voronoi clustering
    feature_universe.voronoi_clustering_median = [ ...
        "voronoi_cluster_010nm_area_median",...
        "voronoi_cluster_010nm_density_median",...
        "voronoi_cluster_010nm_n_locs_median",...
        "voronoi_cluster_010nm_gyration_R_median",...
        "voronoi_cluster_018nm_area_median",...
        "voronoi_cluster_018nm_density_median",...
        "voronoi_cluster_018nm_gyration_R_median",...
        "voronoi_cluster_018nm_n_locs_median",...
        "voronoi_cluster_032nm_area_median",...
        "voronoi_cluster_032nm_density_median",...
        "voronoi_cluster_032nm_gyration_R_median",...
        "voronoi_cluster_032nm_n_locs_median",...
        "voronoi_cluster_056nm_density_median",...
        "voronoi_cluster_056nm_gyration_R_median",...
        "voronoi_cluster_056nm_area_median",...
        "voronoi_cluster_056nm_n_locs_median",...
        "voronoi_cluster_100nm_area_median",...
        "voronoi_cluster_100nm_density_median",...
        "voronoi_cluster_100nm_gyration_R_median",...
        "voronoi_cluster_100nm_n_locs_median"...
        ];
    feature_universe.voronoi_clustering_std = [ ...
        "voronoi_cluster_010nm_area_std",...
        "voronoi_cluster_010nm_density_std",...
        "voronoi_cluster_010nm_gyration_R_std",...
        "voronoi_cluster_010nm_n_locs_std",...
        "voronoi_cluster_018nm_area_std",...
        "voronoi_cluster_018nm_density_std",...
        "voronoi_cluster_018nm_gyration_R_std",...
        "voronoi_cluster_018nm_n_locs_std",...
        "voronoi_cluster_032nm_area_std",...
        "voronoi_cluster_032nm_density_std",...
        "voronoi_cluster_032nm_gyration_R_std",...
        "voronoi_cluster_032nm_n_locs_std",...
        "voronoi_cluster_056nm_area_std",...
        "voronoi_cluster_056nm_density_std",...
        "voronoi_cluster_056nm_gyration_R_std",...
        "voronoi_cluster_056nm_n_locs_std",...
        "voronoi_cluster_100nm_area_std",...
        "voronoi_cluster_100nm_density_std",...
        "voronoi_cluster_100nm_gyration_R_std",...
        "voronoi_cluster_100nm_n_locs_std"...
        ];
    feature_universe.voronoi_clustering_skewness = [ ...
        "voronoi_cluster_010nm_area_skewness",...
        "voronoi_cluster_010nm_density_skewness",...
        "voronoi_cluster_010nm_gyration_R_skewness",...
        "voronoi_cluster_010nm_n_locs_skewness",...
        "voronoi_cluster_018nm_area_skewness",...
        "voronoi_cluster_018nm_density_skewness",...
        "voronoi_cluster_018nm_gyration_R_skewness",...
        "voronoi_cluster_018nm_n_locs_skewness",...
        "voronoi_cluster_032nm_area_skewness",...
        "voronoi_cluster_032nm_density_skewness",...
        "voronoi_cluster_032nm_gyration_R_skewness",...
        "voronoi_cluster_032nm_n_locs_skewness",...
        "voronoi_cluster_056nm_area_skewness",...
        "voronoi_cluster_056nm_density_skewness",...
        "voronoi_cluster_056nm_gyration_R_skewness",...
        "voronoi_cluster_056nm_n_locs_skewness",...
        "voronoi_cluster_100nm_area_skewness",...
        "voronoi_cluster_100nm_density_skewness",...
        "voronoi_cluster_100nm_gyration_R_skewness",...
        "voronoi_cluster_100nm_n_locs_skewness"...
        ];
    feature_universe.voronoi_clustering_n_clusters = [...
        "voronoi_cluster_010nm_clusters_per_area",...
        "voronoi_cluster_018nm_clusters_per_area",...
        "voronoi_cluster_032nm_clusters_per_area",...
        "voronoi_cluster_056nm_clusters_per_area",...
        "voronoi_cluster_100nm_clusters_per_area"...
        ];
    % Heterochromatin cluster analysis
    feature_universe.heterochromatin_cluster_median = [ ...
        "hetero_radius_median",...
        "hetero_density_median",...
        "hetero_n_locs_median"...
        ];
    feature_universe.heterochromatin_cluster_std = [ ...
        "hetero_radius_std",...
        "hetero_density_std",...
        "hetero_n_locs_std"...
        ];    
    feature_universe.heterochromatin_cluster_skewness = [ ...
        "hetero_radius_skewness",...
        "hetero_density_skewness",...
        "hetero_n_locs_skewness"...
        ];
    % Lamin-associated domain (LAD)
    feature_universe.lads_median = [ ...
        "lads_area_median",...
        "lads_density_median",...
        "lads_n_locs_median",...
        "lads_seg_len_median",...
        "lads_seg_thickness_median",...
        "spacing_median",...
        "border_curvature_median"...
        ];
    feature_universe.lads_std = [ ...
        "lads_area_std",...
        "lads_density_std",...
        "lads_n_locs_std",...
        "lads_seg_len_std",...
        "lads_seg_thickness_std",...
        "spacing_std",...
        "border_curvature_std"...
        ];
    feature_universe.lads_skewness = [ ...
        "lads_area_skewness",...
        "lads_density_skewness",...
        "lads_n_locs_skewness",...
        "lads_seg_len_skewness",...
        "lads_seg_thickness_skewness",...
        "spacing_skewness",...
        "border_curvature_skewness"...
        ];
    feature_universe.lads_n = [...
        "lads_n_locs",...
        "non_lads_n_locs",...
        "lads2total_n_locs",...
        "lads_n_clusters",...
        "non_lads_n_clusters",...
        "lads2total_n_clusters"...
        ];
end
%% feature family definition 4
function feature_universe = get_feature_universe_4()
    feature_universe.larger_nucleus = [...
        "major_axis",...
        "minor_axis",...
        "convex_area",...
        "fiber_length",...
        "fiber_width",...
        "elastic_energy",...
        "bending_energy",...
        "nucleus_radius",...
        "perimeter",...
        "convex_perimeter",...
        ];
    feature_universe.less_round_nucleus_shape = [...
        "major_axis_norm_area",...
        "elastic_energy_norm_area",...
        "bending_energy_norm_area"...
        "aspect_ratio",...
        "gyration_radius",...
        "curl",...
        ];
    feature_universe.rounder_nucleus_shape = [...
        "minor_axis_norm_area",...
        "circularity",...
        "convexity",...
        "convex_circularity",...
        "solidity",...
        "rectangularity",...
        "form_ratio",...
        "eigenvalues_ratio",...
        "eigenentropy",...
        ];
    feature_universe.denser_localizations = [...
        "locs_density",...
        "voronoi_density_40",...
        "voronoi_density_70",...
        "reduced_log_voronoi_density_median",...
        "periphery_density",...
        "interior_density",...
        "radial_density_ring_01",...
        "radial_density_ring_02",...
        "radial_density_ring_03",...
        "radial_density_ring_04",...
        "radial_density_ring_05",...
        "radial_density_ring_06",...
        "radial_density_ring_07",...
        "radial_density_ring_08",...
        "radial_density_ring_09",...
        "radial_density_ring_10",...
        "voronoi_cluster_010nm_density_median",...
        "voronoi_cluster_010nm_gyration_R_median",...
        "voronoi_cluster_018nm_density_median",...
        "voronoi_cluster_018nm_gyration_R_median",...
        "voronoi_cluster_032nm_density_median",...
        "voronoi_cluster_032nm_gyration_R_median",...
        "voronoi_cluster_056nm_density_median",...
        "voronoi_cluster_056nm_gyration_R_median",...
        "voronoi_cluster_100nm_density_median",...
        "voronoi_cluster_100nm_gyration_R_median",...
        "lads_density_median",...
        "lads_n_locs",...
        "non_lads_n_locs",...
        "lads2total_n_locs",...
        ];
    feature_universe.denser_clusters = [...
        "periphery_hetero_density",...
        "interior_hetero_density",...
        "radial_heterochromatin_density_ring_01",...
        "radial_heterochromatin_density_ring_02",...
        "radial_heterochromatin_density_ring_03",...
        "radial_heterochromatin_density_ring_04",...
        "radial_heterochromatin_density_ring_05",...
        "radial_heterochromatin_density_ring_06",...
        "radial_heterochromatin_density_ring_07",...
        "radial_heterochromatin_density_ring_08",...
        "radial_heterochromatin_density_ring_09",...
        "radial_heterochromatin_density_ring_10",...
        "lads_n_clusters",...
        "non_lads_n_clusters",...
        "lads2total_n_clusters"...
        "hetero_density_median",...
        "voronoi_cluster_010nm_clusters_per_area",...
        "voronoi_cluster_018nm_clusters_per_area",...
        "voronoi_cluster_032nm_clusters_per_area",...
        "voronoi_cluster_056nm_clusters_per_area",...
        "voronoi_cluster_100nm_clusters_per_area",...
    ];
    feature_universe.more_heterogenous_localization_distribution = [...
        "reduced_log_voronoi_density_std",...
        "radial_density_ring_gradient_major_axis",...
        "radial_density_ring_gradient_minor_axis",...
        "voronoi_cluster_010nm_area_std",...
        "voronoi_cluster_010nm_density_std",...
        "voronoi_cluster_010nm_gyration_R_std",...
        "voronoi_cluster_010nm_n_locs_std",...
        "voronoi_cluster_018nm_area_std",...
        "voronoi_cluster_018nm_density_std",...
        "voronoi_cluster_018nm_gyration_R_std",...
        "voronoi_cluster_018nm_n_locs_std",...
        "voronoi_cluster_032nm_area_std",...
        "voronoi_cluster_032nm_density_std",...
        "voronoi_cluster_032nm_gyration_R_std",...
        "voronoi_cluster_032nm_n_locs_std",...
        "voronoi_cluster_056nm_area_std",...
        "voronoi_cluster_056nm_density_std",...
        "voronoi_cluster_056nm_gyration_R_std",...
        "voronoi_cluster_056nm_n_locs_std",...
        "voronoi_cluster_100nm_area_std",...
        "voronoi_cluster_100nm_density_std",...
        "voronoi_cluster_100nm_gyration_R_std",...
        "voronoi_cluster_100nm_n_locs_std",...
    ];
    feature_universe.more_heterogenous_cluster_distribution = [...
        "radial_heterochromatin_density_ring_gradient_major_axis",...
        "radial_heterochromatin_density_ring_gradient_minor_axis",...
        "hetero_density_std",...
        "hetero_n_locs_std",...
        "lads_area_std",...
        "lads_density_std",...
        "lads_n_locs_std",...
        "lads_seg_len_std",...
        "lads_seg_thickness_std",...
        "spacing_std",...
        "border_curvature_std"...
        "hetero_radius_std",...
    ];
    feature_universe.skewness = [...
        "reduced_log_voronoi_density_skewness",...
        "voronoi_cluster_010nm_area_skewness",...
        "voronoi_cluster_010nm_density_skewness",...
        "voronoi_cluster_010nm_gyration_R_skewness",...
        "voronoi_cluster_010nm_n_locs_skewness",...
        "voronoi_cluster_018nm_area_skewness",...
        "voronoi_cluster_018nm_density_skewness",...
        "voronoi_cluster_018nm_gyration_R_skewness",...
        "voronoi_cluster_018nm_n_locs_skewness",...
        "voronoi_cluster_032nm_area_skewness",...
        "voronoi_cluster_032nm_density_skewness",...
        "voronoi_cluster_032nm_gyration_R_skewness",...
        "voronoi_cluster_032nm_n_locs_skewness",...
        "voronoi_cluster_056nm_area_skewness",...
        "voronoi_cluster_056nm_density_skewness",...
        "voronoi_cluster_056nm_gyration_R_skewness",...
        "voronoi_cluster_056nm_n_locs_skewness",...
        "voronoi_cluster_100nm_area_skewness",...
        "voronoi_cluster_100nm_density_skewness",...
        "voronoi_cluster_100nm_gyration_R_skewness",...
        "voronoi_cluster_100nm_n_locs_skewness",...
    ];
    feature_universe.cluster_size = [...
        "hetero_radius_median",...
        "voronoi_cluster_010nm_area_median",...        
        "voronoi_cluster_018nm_area_median",...        
        "voronoi_cluster_032nm_area_median",...                
        "voronoi_cluster_056nm_area_median",...
        "voronoi_cluster_100nm_area_median",... 
    ];
    feature_universe.lad_size = [...
        "lads_area_median",...
        "lads_n_locs_median",...
        "lads_seg_len_median",...
        "lads_seg_thickness_median",...
        "spacing_median",...
        "border_curvature_median"...
    ];
    feature_universe.n_localizations = [ ...
        "locs_number",...
        "voronoi_cluster_010nm_n_locs_median",...        
        "voronoi_cluster_018nm_n_locs_median",...
        "voronoi_cluster_032nm_n_locs_median",...        
        "voronoi_cluster_056nm_n_locs_median",...
        "voronoi_cluster_100nm_n_locs_median",...
        "hetero_n_locs_median",...
    ];
end
