try
    old_folder = cd('C:\Users\HannahKim\Documents\STORM\SNAP\inside_poly_folder');
    insidepoly_install
    cd(old_folder)
catch ME
    if(strcmp(ME.identifier,'MATLAB:mex:No_compiler_found_link_Win64'))
        msgbox({'Install C compiler for Matlab:',...
            '   1. On the MATLAB Home tab, in the Environment section, click Add-Ons > Get Add-Ons.', ...
            '   2. Search for Min_gW or select from Features.',...
            '   3. Follow instructions on page to install Min_gW-w64 C/C++/Fortran Compiler.',...
            '      Note: Different MATLAB versions may have different installation steps.',...
            '   4. Restart Matlab.'})
    end
    rethrow(ME)
end

